branch-defaults:
  Victor:
    environment: flask-env
  default:
    environment: flask-env
environment-defaults:
  flask-env:
    branch: Victor
    repository: my-blog
  test-env:
    branch: null
    repository: null
global:
  application_name: eb-flask
  branch: null
  default_ec2_keyname: id_rsa
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
